/****** Script to generate the LIBRS Master LRS Spreadsheet  ******/

SELECT DISTINCT la.statute_num AS 'LRS', 
la.statute_desc AS 'LRS_Description' ,
la.lrank AS 'Lrank',
la.ucr AS 'UCR',
la.nibr AS 'Default_NIBRS',
CONCAT('[', SUBSTRING((SELECT DISTINCT '", "' + NIBRS FROM validate v WHERE v.statute_num = la.statute_num FOR XML PATH('') ), 3 , 100), '"]') AS 'Available_NIBRS',
la.lgroup AS 'GP',
la.lpart AS 'PT',
la.lindex AS 'OneA_Index',
la.landxcls AS 'Index_Class',
la.fbindxcl AS 'UCR_Index',
la.ibrndxcl AS 'LIBRS_INDEX',
la.EXPIRATION_DATE AS 'Expiration_Date'
INTO #TempTable
FROM lars la
INNER JOIN validate v on v.statute_num = la.statute_num 

Update #TempTable SET OneA_Index='Agg. Assault' WHERE OneA_Index='AGG ASSAULT'
Update #TempTable SET OneA_Index='Agg. Assault' WHERE OneA_Index='Agg Assault'
Update #TempTable SET OneA_Index='Agg. Assault' WHERE OneA_Index='Agg. Assault'
Update #TempTable SET OneA_Index='Agg. Assault' WHERE OneA_Index='Agg.Assault'
Update #TempTable SET OneA_Index='Arson' WHERE OneA_Index='Arson'
Update #TempTable SET OneA_Index='Burglary' WHERE OneA_Index='Burglary'
Update #TempTable SET OneA_Index='Criminal Homicide' WHERE OneA_Index='Criminal Homicide'
Update #TempTable SET OneA_Index='Larceny Theft' WHERE OneA_Index='larc/theft'
Update #TempTable SET OneA_Index='Larceny Theft' WHERE OneA_Index='Larc/Theft'
Update #TempTable SET OneA_Index='Larceny Theft' WHERE OneA_Index='Larceny'
Update #TempTable SET OneA_Index='Larceny Theft' WHERE OneA_Index='Larceny Theft'
Update #TempTable SET OneA_Index='Larceny Theft' WHERE OneA_Index='LarcenyTheft'
Update #TempTable SET OneA_Index='Murder' WHERE OneA_Index='Murder'
Update #TempTable SET OneA_Index='MV' WHERE OneA_Index='MV'
Update #TempTable SET OneA_Index='Non-Violent' WHERE OneA_Index='Non_Violent'
Update #TempTable SET OneA_Index='Non-Violent' WHERE OneA_Index='NonVio'
Update #TempTable SET OneA_Index='Non-Violent' WHERE OneA_Index='NON-VIOLENT'
Update #TempTable SET OneA_Index='Non-Violent' WHERE OneA_Index='Non-Violent'
Update #TempTable SET OneA_Index='Not a Crime' WHERE OneA_Index='Not a Crime'
Update #TempTable SET OneA_Index='Other' WHERE OneA_Index='other'
Update #TempTable SET OneA_Index='Other' WHERE OneA_Index='Other'
Update #TempTable SET OneA_Index='Other' WHERE OneA_Index='OTHER'
Update #TempTable SET OneA_Index='Person' WHERE OneA_Index='Person'
Update #TempTable SET OneA_Index='Person' WHERE OneA_Index='PERSON'
Update #TempTable SET OneA_Index='Person' WHERE OneA_Index='Person'
Update #TempTable SET OneA_Index='Property' WHERE OneA_Index='Property'
Update #TempTable SET OneA_Index='Rape' WHERE OneA_Index='RAPE'
Update #TempTable SET OneA_Index='Rape' WHERE OneA_Index='Rape'
Update #TempTable SET OneA_Index='Robbery' WHERE OneA_Index='Robbery'
Update #TempTable SET OneA_Index='Simple Assault' WHERE OneA_Index='sim assault'
Update #TempTable SET OneA_Index='Simple Assault' WHERE OneA_Index='Simple Assault'
Update #TempTable SET OneA_Index='Simple Assault' WHERE OneA_Index='SIMPLE ASSAULT'
Update #TempTable SET OneA_Index='Simple Assault' WHERE OneA_Index='SimpleAssault'
Update #TempTable SET OneA_Index='Society' WHERE OneA_Index='Society'
Update #TempTable SET OneA_Index='Society' WHERE OneA_Index='SOCIETY'
Update #TempTable SET OneA_Index='Violent' WHERE OneA_Index='Violent'
Update #TempTable SET OneA_Index='Violent' WHERE OneA_Index='VIOLENT'
Update #TempTable SET OneA_Index='Non-Violent' WHERE OneA_Index='Non Violent'
Update #TempTable SET OneA_Index='Non-Violent' WHERE OneA_Index='non-vio'
Update #TempTable SET OneA_Index='Other' WHERE OneA_Index='Otrher'
Update #TempTable SET OneA_Index='Property' WHERE OneA_Index='Propety'
Update #TempTable SET Index_Class='Agg. Assault' WHERE Index_Class='AGG ASSAULT'
Update #TempTable SET Index_Class='Agg. Assault' WHERE Index_Class='Agg Assault'
Update #TempTable SET Index_Class='Agg. Assault' WHERE Index_Class='Agg. Assault'
Update #TempTable SET Index_Class='Agg. Assault' WHERE Index_Class='Agg.Assault'
Update #TempTable SET Index_Class='Arson' WHERE Index_Class='Arson'
Update #TempTable SET Index_Class='Burglary' WHERE Index_Class='Burglary'
Update #TempTable SET Index_Class='Criminal Homicide' WHERE Index_Class='Criminal Homicide'
Update #TempTable SET Index_Class='Larceny Theft' WHERE Index_Class='larc/theft'
Update #TempTable SET Index_Class='Larceny Theft' WHERE Index_Class='Larc/Theft'
Update #TempTable SET Index_Class='Larceny Theft' WHERE Index_Class='Larceny'
Update #TempTable SET Index_Class='Larceny Theft' WHERE Index_Class='Larceny Theft'
Update #TempTable SET Index_Class='Larceny Theft' WHERE Index_Class='LarcenyTheft'
Update #TempTable SET Index_Class='Murder' WHERE Index_Class='Murder'
Update #TempTable SET Index_Class='MV' WHERE Index_Class='MV'
Update #TempTable SET Index_Class='Non-Violent' WHERE Index_Class='Non_Violent'
Update #TempTable SET Index_Class='Non-Violent' WHERE Index_Class='NonVio'
Update #TempTable SET Index_Class='Non-Violent' WHERE Index_Class='NON-VIOLENT'
Update #TempTable SET Index_Class='Non-Violent' WHERE Index_Class='Non-Violent'
Update #TempTable SET Index_Class='Not a Crime' WHERE Index_Class='Not a Crime'
Update #TempTable SET Index_Class='Other' WHERE Index_Class='other'
Update #TempTable SET Index_Class='Other' WHERE Index_Class='Other'
Update #TempTable SET Index_Class='Other' WHERE Index_Class='OTHER'
Update #TempTable SET Index_Class='Person' WHERE Index_Class='Person'
Update #TempTable SET Index_Class='Person' WHERE Index_Class='PERSON'
Update #TempTable SET Index_Class='Person' WHERE Index_Class='Person'
Update #TempTable SET Index_Class='Property' WHERE Index_Class='Property'
Update #TempTable SET Index_Class='Rape' WHERE Index_Class='RAPE'
Update #TempTable SET Index_Class='Rape' WHERE Index_Class='Rape'
Update #TempTable SET Index_Class='Robbery' WHERE Index_Class='Robbery'
Update #TempTable SET Index_Class='Simple Assault' WHERE Index_Class='sim assault'
Update #TempTable SET Index_Class='Simple Assault' WHERE Index_Class='Simple Assault'
Update #TempTable SET Index_Class='Simple Assault' WHERE Index_Class='SIMPLE ASSAULT'
Update #TempTable SET Index_Class='Simple Assault' WHERE Index_Class='SimpleAssault'
Update #TempTable SET Index_Class='Society' WHERE Index_Class='Society'
Update #TempTable SET Index_Class='Society' WHERE Index_Class='SOCIETY'
Update #TempTable SET Index_Class='Violent' WHERE Index_Class='Violent'
Update #TempTable SET Index_Class='Violent' WHERE Index_Class='VIOLENT'
Update #TempTable SET Index_Class='Non-Violent' WHERE Index_Class='Non Violent'
Update #TempTable SET Index_Class='Non-Violent' WHERE Index_Class='non-vio'
Update #TempTable SET Index_Class='Other' WHERE Index_Class='Otrher'
Update #TempTable SET Index_Class='Property' WHERE Index_Class='Propety'
Update #TempTable SET UCR_Index='Agg. Assault' WHERE UCR_Index='AGG ASSAULT'
Update #TempTable SET UCR_Index='Agg. Assault' WHERE UCR_Index='Agg Assault'
Update #TempTable SET UCR_Index='Agg. Assault' WHERE UCR_Index='Agg. Assault'
Update #TempTable SET UCR_Index='Agg. Assault' WHERE UCR_Index='Agg.Assault'
Update #TempTable SET UCR_Index='Arson' WHERE UCR_Index='Arson'
Update #TempTable SET UCR_Index='Burglary' WHERE UCR_Index='Burglary'
Update #TempTable SET UCR_Index='Criminal Homicide' WHERE UCR_Index='Criminal Homicide'
Update #TempTable SET UCR_Index='Larceny Theft' WHERE UCR_Index='larc/theft'
Update #TempTable SET UCR_Index='Larceny Theft' WHERE UCR_Index='Larc/Theft'
Update #TempTable SET UCR_Index='Larceny Theft' WHERE UCR_Index='Larceny'
Update #TempTable SET UCR_Index='Larceny Theft' WHERE UCR_Index='Larceny Theft'
Update #TempTable SET UCR_Index='Larceny Theft' WHERE UCR_Index='LarcenyTheft'
Update #TempTable SET UCR_Index='Murder' WHERE UCR_Index='Murder'
Update #TempTable SET UCR_Index='MV' WHERE UCR_Index='MV'
Update #TempTable SET UCR_Index='Non-Violent' WHERE UCR_Index='Non_Violent'
Update #TempTable SET UCR_Index='Non-Violent' WHERE UCR_Index='NonVio'
Update #TempTable SET UCR_Index='Non-Violent' WHERE UCR_Index='NON-VIOLENT'
Update #TempTable SET UCR_Index='Non-Violent' WHERE UCR_Index='Non-Violent'
Update #TempTable SET UCR_Index='Not a Crime' WHERE UCR_Index='Not a Crime'
Update #TempTable SET UCR_Index='Other' WHERE UCR_Index='other'
Update #TempTable SET UCR_Index='Other' WHERE UCR_Index='Other'
Update #TempTable SET UCR_Index='Other' WHERE UCR_Index='OTHER'
Update #TempTable SET UCR_Index='Person' WHERE UCR_Index='Person'
Update #TempTable SET UCR_Index='Person' WHERE UCR_Index='PERSON'
Update #TempTable SET UCR_Index='Person' WHERE UCR_Index='Person'
Update #TempTable SET UCR_Index='Property' WHERE UCR_Index='Property'
Update #TempTable SET UCR_Index='Rape' WHERE UCR_Index='RAPE'
Update #TempTable SET UCR_Index='Rape' WHERE UCR_Index='Rape'
Update #TempTable SET UCR_Index='Robbery' WHERE UCR_Index='Robbery'
Update #TempTable SET UCR_Index='Simple Assault' WHERE UCR_Index='sim assault'
Update #TempTable SET UCR_Index='Simple Assault' WHERE UCR_Index='Simple Assault'
Update #TempTable SET UCR_Index='Simple Assault' WHERE UCR_Index='SIMPLE ASSAULT'
Update #TempTable SET UCR_Index='Simple Assault' WHERE UCR_Index='SimpleAssault'
Update #TempTable SET UCR_Index='Society' WHERE UCR_Index='Society'
Update #TempTable SET UCR_Index='Society' WHERE UCR_Index='SOCIETY'
Update #TempTable SET UCR_Index='Violent' WHERE UCR_Index='Violent'
Update #TempTable SET UCR_Index='Violent' WHERE UCR_Index='VIOLENT'
Update #TempTable SET UCR_Index='Non-Violent' WHERE UCR_Index='Non Violent'
Update #TempTable SET UCR_Index='Non-Violent' WHERE UCR_Index='non-vio'
Update #TempTable SET UCR_Index='Other' WHERE UCR_Index='Otrher'
Update #TempTable SET UCR_Index='Property' WHERE UCR_Index='Propety'
Update #TempTable SET Librs_Index='Agg. Assault' WHERE Librs_Index='AGG ASSAULT'
Update #TempTable SET Librs_Index='Agg. Assault' WHERE Librs_Index='Agg Assault'
Update #TempTable SET Librs_Index='Agg. Assault' WHERE Librs_Index='Agg. Assault'
Update #TempTable SET Librs_Index='Agg. Assault' WHERE Librs_Index='Agg.Assault'
Update #TempTable SET Librs_Index='Arson' WHERE Librs_Index='Arson'
Update #TempTable SET Librs_Index='Burglary' WHERE Librs_Index='Burglary'
Update #TempTable SET Librs_Index='Criminal Homicide' WHERE Librs_Index='Criminal Homicide'
Update #TempTable SET Librs_Index='Larceny Theft' WHERE Librs_Index='larc/theft'
Update #TempTable SET Librs_Index='Larceny Theft' WHERE Librs_Index='Larc/Theft'
Update #TempTable SET Librs_Index='Larceny Theft' WHERE Librs_Index='Larceny'
Update #TempTable SET Librs_Index='Larceny Theft' WHERE Librs_Index='Larceny Theft'
Update #TempTable SET Librs_Index='Larceny Theft' WHERE Librs_Index='LarcenyTheft'
Update #TempTable SET Librs_Index='Murder' WHERE Librs_Index='Murder'
Update #TempTable SET Librs_Index='MV' WHERE Librs_Index='MV'
Update #TempTable SET Librs_Index='Non-Violent' WHERE Librs_Index='Non_Violent'
Update #TempTable SET Librs_Index='Non-Violent' WHERE Librs_Index='NonVio'
Update #TempTable SET Librs_Index='Non-Violent' WHERE Librs_Index='NON-VIOLENT'
Update #TempTable SET Librs_Index='Non-Violent' WHERE Librs_Index='Non-Violent'
Update #TempTable SET Librs_Index='Not a Crime' WHERE Librs_Index='Not a Crime'
Update #TempTable SET Librs_Index='Other' WHERE Librs_Index='other'
Update #TempTable SET Librs_Index='Other' WHERE Librs_Index='Other'
Update #TempTable SET Librs_Index='Other' WHERE Librs_Index='OTHER'
Update #TempTable SET Librs_Index='Person' WHERE Librs_Index='Person'
Update #TempTable SET Librs_Index='Person' WHERE Librs_Index='PERSON'
Update #TempTable SET Librs_Index='Person' WHERE Librs_Index='Person'
Update #TempTable SET Librs_Index='Property' WHERE Librs_Index='Property'
Update #TempTable SET Librs_Index='Rape' WHERE Librs_Index='RAPE'
Update #TempTable SET Librs_Index='Rape' WHERE Librs_Index='Rape'
Update #TempTable SET Librs_Index='Robbery' WHERE Librs_Index='Robbery'
Update #TempTable SET Librs_Index='Simple Assault' WHERE Librs_Index='sim assault'
Update #TempTable SET Librs_Index='Simple Assault' WHERE Librs_Index='Simple Assault'
Update #TempTable SET Librs_Index='Simple Assault' WHERE Librs_Index='SIMPLE ASSAULT'
Update #TempTable SET Librs_Index='Simple Assault' WHERE Librs_Index='SimpleAssault'
Update #TempTable SET Librs_Index='Society' WHERE Librs_Index='Society'
Update #TempTable SET Librs_Index='Society' WHERE Librs_Index='SOCIETY'
Update #TempTable SET Librs_Index='Violent' WHERE Librs_Index='Violent'
Update #TempTable SET Librs_Index='Violent' WHERE Librs_Index='VIOLENT'
Update #TempTable SET Librs_Index='Non-Violent' WHERE Librs_Index='Non Violent'
Update #TempTable SET Librs_Index='Non-Violent' WHERE Librs_Index='non-vio'
Update #TempTable SET Librs_Index='Other' WHERE Librs_Index='Otrher'
Update #TempTable SET Librs_Index='Property' WHERE Librs_Index='Propety'


SELECT * FROM #TempTable

Drop table #TempTable
--WHERE la.EXPIRATION_DATE IS NULL OR la.EXPIRATION_DATE >= GETDATE()

SELECT DISTINCT la.statute_num AS 'LRS #', 
la.statute_desc AS 'Actual LRS Description / Another Offense to be Reported' ,
la.lrank AS Lrank,
la.ucr AS UCR,
v.NIBRS AS 'NIBRS',
la.lgroup AS GP,
la.lpart AS PT,
la.lindex AS '1 A Index',
la.landxcls AS 'Index Class',
la.fbindxcl AS 'UCR Index',
la.ibrndxcl AS 'LIBRS INDEX'

FROM lars la
INNER JOIN validate v on v.statute_num = la.statute_num

WHERE la.EXPIRATION_DATE IS NULL OR la.EXPIRATION_DATE >= GETDATE()
